### ISSUE TITLE
code error in students/views.py

### ISSUE THREAD

**Issue by zeeler** [dengguoguo/EducationPlatform#5]
```
Internal Server Error: /submit_register_info_stu/
Traceback (most recent call last):
  File "/Users/litao/Documents/Yuanzhi.Edu/Projects/EducationPlatform/.env/lib/python3.6/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/litao/Documents/Yuanzhi.Edu/Projects/EducationPlatform/.env/lib/python3.6/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/litao/Documents/Yuanzhi.Edu/Projects/EducationPlatform/.env/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/litao/Documents/Yuanzhi.Edu/Projects/EducationPlatform/.env/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/litao/Documents/Yuanzhi.Edu/Projects/EducationPlatform/apps/students/views.py", line 37, in post
    real_name = request.POST.get['real_name']
TypeError: 'method' object is not subscriptable
```
看了下代码：
```
......
            en_name = request.POST.get('en_name')
            passwd = request.POST.get('passwd')
            real_name = request.POST.get['real_name'] # 为啥这里变方括号了？没测试？
            mobile = request.POST.get('mobile')
            gender = request.POST.get('gender')
......
```

**Comment by dengguoguo** [comment]
已经修改！以前是从表单用clean_data拿数据的，后来调试的时候改成request.POST.get()  没有改过来。
